name: Build iOS Library

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - uses: dtolnay/rust-toolchain@stable

      - run: rustup target add aarch64-apple-ios

      - run: cargo build --release --target aarch64-apple-ios

      - uses: actions/upload-artifact@v4
        with:
          name: moonwave-ios
          path: target/aarch64-apple-ios/release/*
